### ISSUE TITLE
Show Pricing on dashboard graph

### ISSUE THREAD

**Issue by jedbridges** [autonomoussoftware/metronome.io#101]
We need to display prices when hovering over each bar in the dashboard graph.
The prices should be a weighted average of the dataset. 

Jordan outlined a potential way to perform the operation:
<img width="980" alt="screen shot 2018-06-29 at 3 34 16 pm" src="https://user-images.githubusercontent.com/1435168/42117635-9ce22d22-7bb2-11e8-8e19-ce2cc114c8d7.png">

Hoverstate:
zpl://screen?sid=5b28381a6af9a4fe7f6bf464&pid=5aea63a29b2863eb66402d92

Tooltip:
zpl://screen?sid=5b36ab6316fcbaad9fa77d6b&pid=5aea63a29b2863eb66402d92

**Comment by gabmontes** [comment]
This request is out-of-date.
