### ISSUE TITLE
WebSite:"https://www.metronome.io/" Sign Error!

### ISSUE THREAD

**Issue by jiulin** [autonomoussoftware/metronome.io#29]
Hi:
WebSite:https://www.metronome.io/

I cannot sign up!

When i enter Email !  The error is  "Unfortunately, an error occurred. Please contact us to subscribe."

**Comment by Dareknotderek** [comment]
Should be fixed by most recent website update.

**Comment by ianaya89** [comment]
Resolved in latest release.
