### ISSUE TITLE
iPhone Testing // Dashboard - Can't tap on Buy Metronome button

### ISSUE THREAD

**Issue by solllve** [autonomoussoftware/metronome.io#33]
<img width="426" alt="screen shot 2018-06-13 at 4 27 46 pm" src="https://user-images.githubusercontent.com/37451497/41383732-ffb60d30-6f26-11e8-823d-c644afe3a634.png">

**Comment by ianaya89** [comment]
I think you can't  because current auction does not have MTN available

**Comment by gabmontes** [comment]
@ianaya89 is right. You can only buy when the auction is running.

**Comment by solllve** [comment]
Right on
