### ISSUE TITLE
iPhone Testing // Apps - Can't load apps (downloads) page. Receiving error

### ISSUE THREAD

**Issue by solllve** [autonomoussoftware/metronome.io#34]
<img width="409" alt="screen shot 2018-06-13 at 4 32 41 pm" src="https://user-images.githubusercontent.com/37451497/41383823-7ebe4b24-6f27-11e8-9785-1ddf7e1d5a57.png">

**Comment by ianaya89** [comment]
Working on this fix

**Comment by ianaya89** [comment]
Solved!
