### ISSUE TITLE
Chrome failure to show current auction metrics

### ISSUE THREAD

**Issue by ianaya89** [autonomoussoftware/metronome.io#57]
![photo5852843975864593905](https://user-images.githubusercontent.com/3258966/41559325-17949d30-731a-11e8-8781-7c13e38735b0.jpg)

**Comment by ianaya89** [comment]
Not able to reproduce, my conclusions are:

- Connected to wrong Ethereum network in MetaMask
- Wrong date-time setup in OS

**Comment by gabmontes** [comment]
Agreed. Closing until we get more information or able to reproduce.
