### ISSUE TITLE
Update Area Chart Data

### ISSUE THREAD

**Issue by jedbridges** [autonomoussoftware/metronome.io#63]
Change the purple area chart to display amount of MET that has been sold

zpl://screen?sid=5b28381a6af9a4fe7f6bf464&pid=5aea63a29b2863eb66402d92

**Comment by gabmontes** [comment]
As per discussion, the chart shall show amount of tokens sold, not percentage.

**Comment by jedbridges** [comment]
Yep! Than you. Updated the issue description 👍
