### ISSUE TITLE
Update Stats section

### ISSUE THREAD

**Issue by jedbridges** [autonomoussoftware/metronome.io#66]
Add Price Cards to the Stats section at the bottom of the Dashboard
I believe Casey had components for these already.

zpl://screen?sid=5b28381a6af9a4fe7f6bf464&pid=5aea63a29b2863eb66402d92

**Comment by pablen** [comment]
<img width="1220" alt="captura de pantalla 2018-07-04 a la s 17 41 39" src="https://user-images.githubusercontent.com/3164763/42293681-5a67301a-7fb2-11e8-8a32-2e78a000c31f.png">
