### ISSUE TITLE
Replace wallet app screenshot on /apps

### ISSUE THREAD

**Issue by jedbridges** [autonomoussoftware/metronome.io#79]
Please replace this image asset found on metronome.io/apps <img width="1006" alt="screen shot 2018-06-20 at 5 50 15 pm" src="https://user-images.githubusercontent.com/1435168/41692026-a2de1f08-74b2-11e8-9343-d977c29860b1.png">

New asset:
App: zpl://screen?sid=5b1718db0fb9498f4256de2f&pid=5aea63a29b2863eb66402d92
Web: https://zpl.io/VDOrQrw

**Comment by ianaya89** [comment]
Solved
